# Generated by Django 5.2.4 on 2025-08-08 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="company",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Company",
                "db_table": "company",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Companydata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_working_project", models.IntegerField()),
                ("total_team", models.IntegerField()),
                ("team_manager", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="serializer.company",
                    ),
                ),
            ],
        ),
    ]
