# Generated by Django 5.2.4 on 2025-08-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("serializer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="companydata",
            table="company_data",
        ),
    ]
