# Generated by Django 5.2.4 on 2025-08-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serializer", "0002_alter_companydata_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(null=True),
        ),
    ]
