# Generated by Django 5.2.4 on 2025-08-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serializer", "0003_company_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("isbn", models.CharField(max_length=13)),
                ("published_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "Book Data",
            },
        ),
    ]
