# Generated by Django 5.2.4 on 2025-08-14 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serializer", "0004_bookdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookdata",
            name="date_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Date Time"
            ),
        ),
        migrations.AddField(
            model_name="bookdata",
            name="read",
            field=models.CharField(auto_created=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bookdata",
            name="published_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
