# Generated by Django 6.0.4 on 2026-04-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0003_blog_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_sended', models.BooleanField(default=False)),
            ],
        ),
    ]
