# Generated by Django 5.2.4 on 2025-08-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="username",
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
