# Generated by Django 5.2.4 on 2025-08-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
    ]
