# Generated by Django 5.2.5 on 2025-09-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_currency_notification_useraddlist'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraddlist',
            table='User Add List',
        ),
    ]
