# Generated by Django 5.2.4 on 2025-08-18 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Country", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("air_port_name", models.CharField(max_length=100)),
                ("pin_code", models.IntegerField(blank=True)),
            ],
            options={
                "db_table": "Country",
            },
        ),
        migrations.CreateModel(
            name="UserTicket",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "from_airport",
                    models.ForeignKey(
                        max_length=100,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="from_airport",
                        to="FVB.country",
                    ),
                ),
                (
                    "to_airport",
                    models.ForeignKey(
                        max_length=100,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="FVB.country",
                    ),
                ),
            ],
            options={
                "db_table": "UserTicket",
            },
        ),
    ]
