# Generated by Django 5.2.4 on 2025-08-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FVB", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courese",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("roll", models.IntegerField()),
                ("course", models.ManyToManyField(to="FVB.courese")),
            ],
        ),
    ]
