# Generated by Django 5.2.4 on 2025-08-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FVB", "0003_order_alter_student_roll_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
