# Generated by Django 5.2.4 on 2025-08-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FVB", "0004_product_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="BookOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                (
                    "Customer_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="FVB.customer"
                    ),
                ),
                (
                    "Items",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="FVB.items"
                    ),
                ),
            ],
        ),
    ]
